services:
  frontend:
    image: flight-diaries-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    image: flight-diaries-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
